use_frameworks!

target 'CPTest_Example' do
    platform :ios, '8.0'
    pod 'CPTest', :path => '../', :subspecs => ['swift']
    
    target 'CPTest_Tests' do
        inherit! :search_paths
    end
end

target 'CPTestTv' do
    platform :tvos, '9.0'
    pod 'CPTest', :path => '../', :subspecs => ['swift']
end
